export const ProductData = [
  {
    id: 1,
    name: "Product A",
    category: "Electronics",
    stock: 50,
    location: "Warehouse 1",
    image: "https://prd.place/400",
  },
  {
    id: 2,
    name: "Product B",
    category: "Furniture",
    stock: 20,
    location: "Warehouse 2",
    image: "https://prd.place/400",
  },
  {
    id: 3,
    name: "Product C",
    category: "Clothing",
    stock: 30,
    location: "Warehouse 3",
    image: "https://prd.place/400",
  },
  {
    id: 4,
    name: "Product D",
    category: "Books",
    stock: 100,
    location: "Warehouse 4",
    image: "https://prd.place/400",
  },
  {
    id: 5,
    name: "Product E",
    category: "Electronics",
    stock: 75,
    location: "Warehouse 1",
    image: "https://prd.place/400",
  },
  {
    id: 6,
    name: "Product F",
    category: "Furniture",
    stock: 15,
    location: "Warehouse 2",
    image: "https://prd.place/400",
  },
  {
    id: 7,
    name: "Product G",
    category: "Clothing",
    stock: 45,
    location: "Warehouse 3",
    image: "https://prd.place/400",
  },
  {
    id: 8,
    name: "Product H",
    category: "Books",
    stock: 80,
    location: "Warehouse 4",
    image: "https://prd.place/400",
  },
  {
    id: 9,
    name: "Product I",
    category: "Electronics",
    stock: 60,
    location: "Warehouse 1",
    image: "https://prd.place/400",
  },
  {
    id: 10,
    name: "Product J",
    category: "Furniture",
    stock: 25,
    location: "Warehouse 2",
    image: "https://prd.place/400",
  },
  {
    id: 11,
    name: "Product K",
    category: "Clothing",
    stock: 35,
    location: "Warehouse 3",
    image: "https://prd.place/400",
  },
  {
    id: 12,
    name: "Product L",
    category: "Books",
    stock: 90,
    location: "Warehouse 4",
    image: "https://prd.place/400",
  },
  {
    id: 13,
    name: "Product M",
    category: "Electronics",
    stock: 70,
    location: "Warehouse 1",
    image: "https://prd.place/400",
  },
  {
    id: 14,
    name: "Product N",
    category: "Furniture",
    stock: 18,
    location: "Warehouse 2",
    image: "https://prd.place/400",
  },
  {
    id: 15,
    name: "Product O",
    category: "Clothing",
    stock: 40,
    location: "Warehouse 3",
    image: "https://prd.place/400",
  },
  {
    id: 16,
    name: "Product P",
    category: "Books",
    stock: 85,
    location: "Warehouse 4",
    image: "https://prd.place/400",
  },
  {
    id: 17,
    name: "Product Q",
    category: "Electronics",
    stock: 55,
    location: "Warehouse 1",
    image: "https://prd.place/400",
  },
  {
    id: 18,
    name: "Product R",
    category: "Furniture",
    stock: 22,
    location: "Warehouse 2",
    image: "https://prd.place/400",
  },
  {
    id: 19,
    name: "Product S",
    category: "Clothing",
    stock: 38,
    location: "Warehouse 3",
    image: "https://prd.place/400",
  },
  {
    id: 20,
    name: "Product T",
    category: "Books",
    stock: 95,
    location: "Warehouse 4",
    image: "https://prd.place/400",
  },
  {
    id: 21,
    name: "Product U",
    category: "Electronics",
    stock: 65,
    location: "Warehouse 1",
    image: "https://prd.place/400",
  },
  {
    id: 22,
    name: "Product V",
    category: "Furniture",
    stock: 17,
    location: "Warehouse 2",
    image: "https://prd.place/400",
  },
  {
    id: 23,
    name: "Product W",
    category: "Clothing",
    stock: 42,
    location: "Warehouse 3",
    image: "https://prd.place/400",
  },
  {
    id: 24,
    name: "Product X",
    category: "Books",
    stock: 78,
    location: "Warehouse 4",
    image: "https://prd.place/400",
  },
  {
    id: 25,
    name: "Product Y",
    category: "Electronics",
    stock: 48,
    location: "Warehouse 1",
    image: "https://prd.place/400",
  },
  {
    id: 26,
    name: "Product Z",
    category: "Furniture",
    stock: 28,
    location: "Warehouse 2",
    image: "https://prd.place/400",
  },
  {
    id: 27,
    name: "Product AA",
    category: "Clothing",
    stock: 32,
    location: "Warehouse 3",
    image: "https://prd.place/400",
  },
  {
    id: 28,
    name: "Product AB",
    category: "Books",
    stock: 82,
    location: "Warehouse 4",
    image: "https://prd.place/400",
  },
  {
    id: 29,
    name: "Product AC",
    category: "Electronics",
    stock: 58,
    location: "Warehouse 1",
    image: "https://prd.place/400",
  },
  {
    id: 30,
    name: "Product AD",
    category: "Furniture",
    stock: 23,
    location: "Warehouse 2",
    image: "https://prd.place/400",
  },
  {
    id: 31,
    name: "Product AE",
    category: "Clothing",
    stock: 37,
    location: "Warehouse 3",
    image: "https://prd.place/400",
  },
  {
    id: 32,
    name: "Product AF",
    category: "Books",
    stock: 92,
    location: "Warehouse 4",
    image: "https://prd.place/400",
  },
  {
    id: 33,
    name: "Product AG",
    category: "Toys",
    stock: 110,
    location: "Warehouse 5",
    image: "https://prd.place/400",
  },
];
